from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="cotkg-ids",
    version="0.2.0",
    author="Chen Xingqiang",
    author_email="chen.xingqiang@iechor.com",
    description="A network intrusion detection system using Chain of Thought, knowledge graphs and GraphSAGE",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/chenxingqiang/cotkg-network-intrusion-detection",
    project_urls={
        "Bug Tracker": "https://github.com/chenxingqiang/cotkg-network-intrusion-detection/issues",
        "Documentation": "https://github.com/chenxingqiang/cotkg-network-intrusion-detection/wiki",
        "Source Code": "https://github.com/chenxingqiang/cotkg-network-intrusion-detection",
    },
    packages=find_packages(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Topic :: Security",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.7",
    install_requires=[
        "numpy",
        "pandas",
        "scikit-learn",
        "imbalanced-learn",
        "joblib",
        "pyarrow",
        "torch>=1.9.0",
        "torch-geometric",
        "networkx",
        "py2neo",
        "matplotlib",
        "seaborn",
        "tsfresh",
        "shap",
        "transformers",
        "openai",
        "anthropic",
        "dashscope",
        "zhipuai",
        "httpcore[socks]",
        "ollama",
        "tqdm",
        "jupyter==1.0.0",
        "pytest",
        "requests",
    ],
    include_package_data=True,
    package_data={
        'cotkg_ids': [
            'config/*.py',
            'data/raw/*',
            'data/processed/*',
            'scripts/*',
        ],
    },
    entry_points={
        'console_scripts': [
            'cotkg-ids=cotkg_ids.main:main',
            'cotkg-ids-setup=cotkg_ids.scripts.setup_ollama:main',
        ],
    },
)
